steps:
  # Build container image new version
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcallcloud/flaskapp:$COMMIT_SHA', '.']
  # Build container image latest tag
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcallcloud/flaskapp:latest', '.']

  # Waiting for approval
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'builds', 'wait', '$BUILD_ID', '--approval-prompt', 'manual']
  # Push container image new verison to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcallcloud/flaskapp:$COMMIT_SHA']
  # Push container image latest tag
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcallcloud/flaskapp:latest']
serviceAccount: 'cloudbuildsa@mimetic-retina-410109.iam.gserviceaccount.com'
logsBucket: 'gs://building-mimetic-retina-410109'