steps:
  # Build container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcallcloud:$COMMIT_SHA', '.']
  # Push container image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/gcallcloud:latest']
serviceAccount: 'cloudbuildsa@mimetic-retina-410109.iam.gserviceaccount.com'
logsBucket: 'gs://building-mimetic-retina-410109'