steps:
  # Build container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag', 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcallcloud:$COMMIT_SHA', '.']
  # Push container image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-southwest1-docker.pkg.dev/$PROJECT_ID/gcallcloud:$COMMIT_SHA']
serviceAccount: 'cloudbuildsa@mimetic-retina-410109.iam.gserviceaccount.com'
logsBucket: 'gs://cloudbuild-mimetic-retina-410109'
  